services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # prevent host node_modules from overriding container's
    profiles: ["dev"]

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    profiles: ["prod"]